// Pure Markdown rendering of a KAT run. The document is generated, never hand-edited.

const cell = (v) =>
  String(v ?? '—')
    .replaceAll('|', '\\|')
    .replaceAll('\n', ' ');

/**
 * Renders the conformance report.
 * @param {{revision: {commit: string, dirty: boolean}, command: string, startedAt: string,
 *   runtime: Record<string,string>, algorithms: any[], failureModes: any[], summary: any}} run
 * @returns {string}
 */
export function renderMarkdown(run) {
  const out = [];
  out.push('# Known-answer test (KAT) conformance report');
  out.push('');
  out.push('<!-- GENERATED by assurance/kat/run.mjs. Do not edit by hand; re-run the command. -->');
  out.push('');
  out.push(
    '**Scope.** Selected published known-answer vectors run against the cryptographic primitives the product calls (Node.js `node:crypto` / WebCrypto backed by OpenSSL, and the laboratory-only `@noble/post-quantum` provider). This is engineering conformance evidence only. It is **not** CAVP/ACVP algorithm validation, **not** FIPS 140-3 module validation and **not** SAG evaluation; none of those is held.',
  );
  out.push('');
  out.push('| Field | Value |');
  out.push('| --- | --- |');
  out.push(`| Command | \`${cell(run.command)}\` |`);
  out.push(
    `| Commit | \`${cell(run.revision.commit)}\`${run.revision.dirty ? ' (working tree had uncommitted changes)' : ' (clean working tree)'} |`,
  );
  out.push(`| Started | ${cell(run.startedAt)} |`);
  for (const [k, v] of Object.entries(run.runtime)) out.push(`| ${cell(k)} | ${cell(v)} |`);
  out.push(
    `| Totals | ${run.summary.casesPassed}/${run.summary.casesRun} vector cases passed; ${run.summary.failureModesPassed}/${run.summary.failureModes} failure-mode checks passed |`,
  );
  out.push('');
  out.push('## Per algorithm');
  out.push('');
  out.push('| Algorithm | Standard | Status | Sets run | Sets not run |');
  out.push('| --- | --- | --- | --- | --- |');
  for (const a of run.algorithms) {
    const ran = a.sets.filter((s) => s.status !== 'NOT-RUN').length;
    out.push(
      `| ${cell(a.name)} | ${cell(a.standard)} | **${a.status}**${a.status === 'PASS' && a.sets.some((s) => s.status === 'NOT-RUN') ? ' (partial)' : ''} | ${ran} | ${a.sets.length - ran} |`,
    );
  }
  out.push('');
  out.push('## Per vector set');
  out.push('');
  out.push(
    '| Algorithm | Set | Implementation | Status | Cases | Source | Version | File SHA-256 / reason |',
  );
  out.push('| --- | --- | --- | --- | --- | --- | --- | --- |');
  for (const a of run.algorithms)
    for (const s of a.sets)
      out.push(
        `| ${cell(a.name)} | ${cell(s.set)} | ${cell(s.implementation)} | **${s.status}** | ${s.status === 'NOT-RUN' ? '—' : `${s.passed}/${s.cases}`} | ${cell(s.source)} | ${cell(s.version)} | ${s.status === 'NOT-RUN' ? cell(s.reason) : `\`${cell(s.fileSha256)}\``} |`,
      );
  out.push('');
  const failed = run.algorithms.flatMap((a) =>
    a.sets.flatMap((s) => (s.failures ?? []).map((f) => ({ a: a.name, s: s.set, ...f }))),
  );
  if (failed.length) {
    out.push('## Failed cases');
    out.push('');
    for (const f of failed)
      out.push(`- ${cell(f.a)} / ${cell(f.s)} / case ${cell(f.id)}: ${cell(f.reason)}`);
    out.push('');
  }
  out.push('## Failure-mode checks');
  out.push('');
  out.push(
    'Deterministic negative tests: each must be rejected (or, for KEM implicit rejection, yield a different shared secret).',
  );
  out.push('');
  out.push('| Algorithm | Check | Status | Detail |');
  out.push('| --- | --- | --- | --- |');
  for (const f of run.failureModes)
    out.push(`| ${cell(f.algorithm)} | ${cell(f.check)} | **${f.status}** | ${cell(f.detail)} |`);
  out.push('');
  out.push('## What this does not show');
  out.push('');
  out.push('- Vector coverage is the subset listed above; NOT-RUN rows are gaps, not passes.');
  out.push(
    '- Passing KATs on OpenSSL-backed Node.js says nothing about a FIPS 140-3 module boundary, self-tests, or operational environment (see `docs/assurance/fips-sag-gap-analysis.md`).',
  );
  out.push(
    '- Laboratory PQC providers are excluded from releases (`packages/pqc-lab`); their KAT results do not make them deployable.',
  );
  out.push('');
  return out.join('\n');
}
